from app.rag.document_loader import chunk_documents, load_markdown_documents
from app.rag.retriever import answer_from_context, retrieve


def test_load_markdown_documents_reads_three_files():
    documents = load_markdown_documents()

    assert len(documents) == 3
    assert {document["source"] for document in documents} == {
        "kpi_dictionary.md",
        "data_dictionary.md",
        "business_rules.md",
    }


def test_chunk_documents_create_chunks_with_sources():
    chunks = chunk_documents(load_markdown_documents())

    assert chunks
    assert all(chunk["source"] for chunk in chunks)
    assert all(chunk["chunk_id"] for chunk in chunks)
    assert all(chunk["text"] for chunk in chunks)


def test_retrieve_revenue_returns_relevant_chunk():
    chunks = retrieve("Que signifie Revenue ?", k=3)

    assert chunks
    assert any("Revenue" in chunk["text"] for chunk in chunks)
    assert any(chunk["source"] in {"kpi_dictionary.md", "business_rules.md"} for chunk in chunks)


def test_retrieve_margin_returns_formula_chunk():
    chunks = retrieve("Comment calcule-t-on la marge ?", k=3)

    assert chunks
    assert any("Margin" in chunk["text"] or "Revenue - Cost" in chunk["text"] for chunk in chunks)


def test_retrieve_enterprise_returns_customer_segment_chunk():
    chunks = retrieve("Qu'est-ce qu'un client Enterprise ?", k=3)

    assert chunks
    assert any("Enterprise" in chunk["text"] for chunk in chunks)
    assert any(chunk["source"] == "data_dictionary.md" for chunk in chunks)


def test_retrieve_top_customer_returns_business_rule_chunk():
    chunks = retrieve("Comment definir un top customer ?", k=3)

    assert chunks
    assert any("top customer" in chunk["text"].lower() for chunk in chunks)


def test_unknown_question_returns_no_chunk():
    chunks = retrieve("Quelle est la couleur du logo officiel ?", k=3)

    assert chunks == []


def test_answer_from_context_contains_sources():
    chunks = retrieve("Que signifie Revenue ?", k=2)
    result = answer_from_context("Que signifie Revenue ?", chunks)

    assert result["answer"]
    assert result["sources"]
    assert all(source.endswith(".md") for source in result["sources"])
    assert "[" not in result["answer"]
    assert "##" not in result["answer"]


def test_answer_from_context_for_unknown_question_is_safe():
    result = answer_from_context("Question inconnue", [])

    assert result["answer"] == "Je n'ai pas trouve cette information dans la base documentaire."
    assert result["sources"] == []


def test_local_rag_has_no_llm_dependency_in_usage():
    chunks = retrieve("Comment calcule-t-on la marge ?", k=3)
    result = answer_from_context("Comment calcule-t-on la marge ?", chunks)

    assert result["answer"]
    assert "openai" not in result["answer"].lower()


def test_answer_revenue_is_concise_and_contains_formula():
    chunks = retrieve("Que signifie Revenue ?", k=3)
    result = answer_from_context("Que signifie Revenue ?", chunks)

    assert "Revenue is the total sales amount generated by transactions." in result["answer"]
    assert "Formule :" in result["answer"]
    assert "Quantity x Unit Price" in result["answer"]


def test_answer_margin_contains_definition_and_formula():
    chunks = retrieve("Comment calcule-t-on la marge ?", k=3)
    result = answer_from_context("Comment calcule-t-on la marge ?", chunks)

    assert "Margin is the gross profit generated by sales." in result["answer"]
    assert "Formule : Margin = Revenue - Cost" in result["answer"]


def test_answer_margin_percent_contains_formula():
    chunks = retrieve("Que signifie Margin % ?", k=3)
    result = answer_from_context("Que signifie Margin % ?", chunks)

    assert "Margin %" in result["answer"]
    assert "Margin / Revenue x 100" in result["answer"]


def test_answer_difference_between_revenue_and_margin_is_structured():
    chunks = retrieve("Quelle est la difference entre Revenue et Margin ?", k=3)
    result = answer_from_context("Quelle est la difference entre Revenue et Margin ?", chunks)

    assert "Revenue :" in result["answer"]
    assert "Margin :" in result["answer"]
    assert "Formule de la marge" in result["answer"]


def test_answer_top_customer_returns_business_rule():
    chunks = retrieve("Comment definit-on un top customer ?", k=3)
    result = answer_from_context("Comment definit-on un top customer ?", chunks)

    assert "A top customer is ranked by total Revenue" in result["answer"]
    assert "business_rules.md" in result["sources"]


def test_answer_enterprise_returns_segment_definition():
    chunks = retrieve("Qu'est-ce qu'un client Enterprise ?", k=3)
    result = answer_from_context("Qu'est-ce qu'un client Enterprise ?", chunks)

    assert "Enterprise" in result["answer"]
    assert "larger order volumes" in result["answer"]
    assert "data_dictionary.md" in result["sources"]


def test_answer_ebitda_is_safe_and_empty_sources():
    chunks = retrieve("Que signifie EBITDA ?", k=3)
    result = answer_from_context("Que signifie EBITDA ?", chunks)

    assert result["answer"] == "Je n'ai pas trouve cette information dans la base documentaire."
    assert result["sources"] == []
